// src/routes/__layout.svelte
<style lang="scss">
  .container {
    margin: 0 auto;
    max-width: $content-width - $spacing * 2;
    padding: 0 $spacing;

    @media screen and (max-width: $large-width) {
      max-width: $content-width - $spacing;
      padding: 0 $spacing;
    }
  }
</style>

<script>
  import Footer from "$components/Footer.svelte"
  import Header from "$components/Header.svelte"

  import "$styles/index.scss"
</script>

<div class="container">
  <Header />
  <slot />
  <Footer />
</div>

// src/components/common/layout.tsx
import React from "react";
import styled from "styled-components";
import SEO from "./seo";
import Footer from "./footer";
import Header from "./header";
import GlobalStyle from "../../styles/global";
import c from "../../styles/constants";

interface Props {
  children: React.ReactNode;
}

const Container = styled.div`
  margin: 0 auto;
  max-width: calc(${c.size.contentWidth}px - ${c.size.spacingUnit * 2}px);
  padding: 0 ${c.size.spacingUnit}px;

  @media screen and (max-width: ${c.size.largeWidth}px) {
    max-width: calc(${c.size.contentWidth}px - ${c.size.spacingUnit}px);
    padding: 0 ${c.size.spacingUnit / 2}px;
  }
`;

const Layout: React.FC<Props> = ({ children }) => {
  return (
    <React.StrictMode>
      <GlobalStyle />
      <SEO />
      <Container>
        <Header />
        {children}
        <Footer />
      </Container>
    </React.StrictMode>
  );
};

export default Layout;
